core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm
from .views import logout_view

app_name = 'core'

urlpatterns = [
    path('', views.homePage, name='homePage'),
    path('about/', views.aboutPage, name='aboutPage'),
    path('signup/', views.signupPage, name='signupPage'),
    path('login/', auth_views.LoginView.as_view(template_name='core/loginPage.html', authentication_form=LoginForm), name='loginPage'),
    path('logout/', logout_view, name='logout'),
    path('category/<int:pk>/', views.categoryRecipes, name='categoryRecipes'),
]

receipt_website/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('recipes/', include('recipe.urls')),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe/urls.py
from django.urls import path
from . import views

app_name = 'recipe'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
    path('addRecipe/', views.addRecipe, name='addRecipe'),
    path('<int:pk>/delete/', views.deleteRecipe, name='deleteRecipe'),
    path('<int:pk>/edit/', views.editRecipe, name='editRecipe'),
    path('search/', views.searchRecipe, name='searchRecipe'),
    path('<int:pk>/likeRecipe/', views.likeRecipe, name='likeRecipe'),
    path('likedRecipes/', views.likedRecipes, name='likedRecipes'),
    path('deleteComment/<int:pk>/', views.deleteComment, name='deleteComment')
]

recipe/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class Recipe(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    ingredients = models.TextField()
    directions = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='recipe_images', blank=True)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    n_of_likes = models.IntegerField(default=0)
    difficulty = models.IntegerField(default=1)

    def __str__(self):
        return self.name


class LikeRecipe(models.Model):
    recipe_id = models.CharField(max_length=500)
    username = models.CharField(max_length=500)

    def __str__(self):
        return self.username


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    recipe = models.ForeignKey('Recipe', on_delete=models.CASCADE)
    content = models.TextField(max_length=100)

    def __str__(self):
        return self.user.username

recipe/forms.py
from django import forms
from .models import Category, Recipe, Comment

INPUT_CLASS = 'form-control py-2 px-3'

class newRecipeForm(forms.ModelForm):
    difficulty = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 6)])
    class Meta:
        model = Recipe
        fields = ('name', 'description', 'ingredients', 'directions', 'category','difficulty', 'image')

        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASS,
            }),
            'name': forms.TextInput(attrs={
                'placeholder': 'es. Pizza Margherita',
                'class': INPUT_CLASS,
            }),
            'description': forms.Textarea(attrs={
                'placeholder': 'es. Best pizza ever',
                'class': INPUT_CLASS,
            }),
            'ingredients': forms.Textarea(attrs={
                'placeholder': 'es. 1 cup of flour, 1 cup of water, 1 cup of salt',
                'class': INPUT_CLASS,
            }),
            'directions': forms.Textarea(attrs={
                'placeholder': 'es. 1. Mix the flour, water and salt in a bowl. 2. Bake for 30 minutes',
                'class': INPUT_CLASS,
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASS,
            })
        }


class editRecipeForm(forms.ModelForm):
    difficulty = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 6)])
    class Meta:
        model = Recipe
        fields = ('name', 'description', 'ingredients', 'directions', 'difficulty', 'image')

        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': 'es. Pizza Margherita',
                'class': INPUT_CLASS,
            }),
            'description': forms.Textarea(attrs={
                'placeholder': 'es. Best pizza ever',
                'class': INPUT_CLASS,
            }),
            'ingredients': forms.Textarea(attrs={
                'placeholder': 'es. 1 cup of flour, 1 cup of water, 1 cup of salt',
                'class': INPUT_CLASS,
            }),
            'directions': forms.Textarea(attrs={
                'placeholder': 'es. 1. Mix the flour, water and salt in a bowl. 2. Bake for 30 minutes',
                'class': INPUT_CLASS,
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASS,
            })
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

        widgets = {
            'content': forms.Textarea(attrs={
                'placeholder': 'Write your comment here...',
                'class': INPUT_CLASS,
            })
        }

recipe/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_protect

from .models import Category, Recipe, LikeRecipe, Comment
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .forms import newRecipeForm, editRecipeForm, CommentForm

# Create your views here.

@csrf_protect
def detail(request, pk):
    recipe = get_object_or_404(Recipe, pk=pk)
    related_recipes = Recipe.objects.filter(category=recipe.category).exclude(pk=pk)[0:4]
    comments = Comment.objects.filter(recipe=recipe).order_by('-date')
    allrecipes = Recipe.objects.all()
    liked_rec = LikeRecipe.objects.filter(username=request.user.username, recipe_id=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            if request.user.is_authenticated:
                comment.user = request.user
            else:
                comment.user = None
            comment.recipe = recipe
            comment.save()
            return redirect('recipe:detail', pk=recipe.pk)
    else:
        form = CommentForm()

    return render(request, 'recipe/detail.html', {
        'recipe': recipe,
        'related_recipes': related_recipes,
        'form': form,
        'comments': comments,
        'allrecipes': allrecipes,
        'liked_rec': liked_rec
    })

@csrf_protect
@login_required
def addRecipe(request):
    if request.method == 'POST':
        form = newRecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.created_by = request.user
            recipe.save()
            return redirect('recipe:detail', pk=recipe.pk)
    else:
            form = newRecipeForm()

    return render(request, 'recipe/addRecipe.html', {
        'form': form
    })

@csrf_protect
@login_required
def deleteRecipe(request, pk):
    recipe = get_object_or_404(Recipe, pk=pk, created_by=request.user)
    recipe.delete()

    return redirect('dashboard:dashboardPage')

@csrf_protect
@login_required
def editRecipe(request, pk):
    recipe = get_object_or_404(Recipe, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = editRecipeForm(request.POST, request.FILES, instance=recipe)
        if form.is_valid():
            recipe.save()
            return redirect('recipe:detail', pk=recipe.pk)
    else:
            form = editRecipeForm(instance=recipe)

    return render(request, 'recipe/editRecipe.html', {
        'form': form
    })

@csrf_protect
def searchRecipe(request):
    query = request.GET.get('query', '')
    recipes = Recipe.objects.all()
    allrecipes = Recipe.objects.all()

    if query:
        recipes = Recipe.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request, 'recipe/searchRecipe.html', {
        'recipes': recipes,
        'query': query,
        'allrecipes': allrecipes
    })

@login_required
def likeRecipe(request, pk):
    username = request.user.username
    recipe_id = pk

    recipe = Recipe.objects.get(id=recipe_id)

    like_filter = LikeRecipe.objects.filter(recipe_id=recipe_id, username=username).first()

    if not like_filter:
        like = LikeRecipe.objects.create(recipe_id=recipe_id, username=username)
        like.save()
        recipe.n_of_likes += 1
        recipe.save()
        return redirect('/recipes/' + str(recipe_id) + '/')
    else:
        like_filter.delete()
        recipe.n_of_likes -= 1
        recipe.save()
        return redirect('/recipes/' + str(recipe_id) + '/')


@csrf_protect
@login_required
def likedRecipes(request):
    username = request.user.username
    recipes = LikeRecipe.objects.filter(username=username)
    liked_recipes = Recipe.objects.filter(id__in=recipes.values_list('recipe_id', flat=True))
    all_recipes = Recipe.objects.exclude(id__in=liked_recipes.values_list('id', flat=True)).order_by('?')
    allrecipes = Recipe.objects.all()

    return render(request, 'recipe/likedRecipes.html', {
        'liked_recipes': liked_recipes,
        'all_recipes': all_recipes,
        'allrecipes': allrecipes
    })

@csrf_protect
@login_required
def deleteComment(request, pk):
    comment = get_object_or_404(Comment, pk=pk, user=request.user)
    recipe_pk = comment.recipe.pk
    comment.delete()

    return redirect('recipe:detail', pk=recipe_pk)

recipe/templates/recipe/addRecipe.html
{% extends 'core/base.html' %}

{% block title %}
   New Recipe
{% endblock %}

{% block content %}
    <div class="px-3">
   <h1 class="pt-3">Insert your new recipe here!</h1>

   <form method="POST" action="." enctype="multipart/form-data">
      {% csrf_token %}

       <div class="p-4 fw-bold">
           {{ form.as_p }}
       </div>

   {% if form.errors or form.non_field_errors %}
                    <div class="mb-3 p-4 bg-danger rounded-3">
                        {% for field in form %}
                            {{ field.errors }}
                        {% endfor %}
                    {{ form.non_field_errors }}
                    </div>
                {% endif %}
    <div class="text-center">
        <button type="submit" class="btn btn-success px-3 text-center px-5 fw-bold">Submit</button>
    </div>
   </form>
    </div>
{% endblock %}
```

recipe/templates/recipe/detail.html
{% extends 'core/base.html' %}

{% block title %} {{ recipe.name }} {% endblock %}

{% block content %}
    <div class="px-3">
    <div class="row pt-2">
        <div class="col-6">
            <h1> <i>{{ recipe.name }} </i></h1>
        </div>
        <div class="col-3 py-3" style="display: flex; flex-direction: row">
            <b class="p-2">Difficulty:</b>
            {% for r in allrecipes %}
                {% if forloop.counter <= recipe.difficulty %}
                    <i class="bi bi-star-fill text-warning" style="font-size: 1.5rem"></i>
                {% endif %}
            {% endfor %}
        </div>
           <div class="col-3 pt-3">
               {% if request.user == recipe.created_by %}
                   <h4>{{ recipe.category }} | Yours </h4>
               {% else %}
                <h4>{{ recipe.category }} | by {{ recipe.created_by }}</h4>
                {% endif %}
           </div>

        <hr>

    <div class="row">
    <div class="col-6">
        <img src="{{ recipe.image.url }}" alt="{{ recipe.name }}" class="img-fluid rounded-4" style="width: 100%">
    </div>

    <div class="col-6 px-2">
        <h3><b>Description:</b></h3>
        {{ recipe.description }}
        <h3 class="pt-3"><b>Ingredients:</b></h3>
        {{ recipe.ingredients }}
        <h3 class="pt-3"><b>Directions:</b></h3>
        <p>{{ recipe.directions }}</p>

        <div class="favourites pt-5" style="display: flex; justify-content: flex-end;">

        {% if recipe.n_of_likes == 0 %}
            <p class="px-3 py-2"><b> No likes yet :( </b></p>
        {% elif recipe.n_of_likes == 1%}
            <p class="px-3 py-2"><b>Liked by {{ recipe.n_of_likes }} student</b></p>
        {% else %}
            <p class="px-3 py-2"><b>Liked by {{ recipe.n_of_likes }} students</b></p>
        {% endif %}


        {% if request.user.is_authenticated %}
            {% if liked_rec %}
                <a href="{% url 'recipe:likeRecipe' recipe.id %}" class="add-to-fav" title="Add to favourites">
                <i class="bi bi-suit-heart-fill text-danger" style="font-size: 2rem"></i>
            </a>
                {% else %}
            <a href="{% url 'recipe:likeRecipe' recipe.id %}" class="add-to-fav" title="Add to favourites">
                <i class="bi bi-suit-heart text-danger" style="font-size: 2rem"></i>
            </a>
                {% endif %}
        {% else %}
            <a class="login-btn py-1" href="{% url 'core:loginPage' %}">
                        <button type="button" class="btn btn-outline-primary rounded-5 px-4 ">Login to like the recipe</button>
                    </a>
        {% endif %}
            <a href="#" class="share-btn" title="Share">
                <i class="bi bi-share px-3 text-dark" style="font-size: 2rem"></i>
            </a>

            {% if request.user == recipe.created_by %}
            <a href="{% url 'recipe:deleteRecipe' recipe.id %}" class="delete-btn" title="Delete">
            <button type="button" href="#" class="btn btn-danger text-light text-center rounded-5 px-4">
                <div class="d-flex align-items-center justify-content-center">
               Delete <i class="bi bi-trash text-light" style="font-size: 1.5rem"></i>
                </div>
            </button>
            </a>

                <a href="{% url 'recipe:editRecipe' recipe.id %}" class="edit-btn px-2" title="Edit">
            <button type="button" href="#" class="btn btn-warning text-light text-center rounded-5 px-4">
                <div class="d-flex align-items-center justify-content-center">
               Edit <i class="bi bi-pencil-fill" style="font-size: 1.5rem"></i>
                </div>
            </button>
            </a>
            {% endif %}
         </div>
    </div>
    </div>

    <div class="row">
    {% if request.user.is_authenticated %}
        <div class="col-6">
            <form method="POST" action="." enctype="multipart/form-data">
                  {% csrf_token %}

                   <div class="p-4 fw-bold">
                       <h3><b>Leave a comment:</b></h3>
                       <div class="text-white">{{ form.as_p }}</div>
                   </div>

                   {% if form.errors or form.non_field_errors %}
                                    <div class="mb-3 p-4 bg-danger rounded-3">
                                        {% for field in form %}
                                            {{ field.errors }}
                                        {% endfor %}
                                    {{ form.non_field_errors }}
                                    </div>
                   {% endif %}
                <div class="text-center">
                    <button type="submit" class="btn btn-success px-3 text-center fw-bold">Leave a comment</button>
                </div>
            </form>
        </div>
    {% else %}
        <div class="col-6">
            <div class="p-4 fw-bold">
                <a class="login-btn py-1" href="{% url 'core:loginPage' %}">
                        <button type="button" class="btn btn-outline-primary rounded-5 px-4 ">Login to leave a comment</button>
                    </a>
            </div>
        </div>
    {% endif %}
        <div class="col-6 pt-3">
            <h3><b>Comments:</b></h3>
            {% for comment in comments %}
                <div class="card">
                    <div class="card-header" style="display: flex; flex-direction: row; justify-content: space-between">
                        <b>{{ comment.user.username }}</b>
                        <div>{{ comment.date }}</div>
                    </div>
                    <div class="card-body" style="display: flex; flex-direction: row; justify-content: space-between">
                        <i>{{ comment.content }}</i>
                        {% if request.user == comment.user %}
                            <a href="{% url 'recipe:deleteComment' comment.id %}" class="delete-btn" title="Delete">
                                <i class="bi bi-trash text-danger" style="font-size: 1.5rem"></i>
                            </a>
                        {% endif %}
                    </div>
                </div>

            {% endfor %}
        </div>


    </div>

        <div class="row pt-5">
        <h4 class="text-center py-2 bg-secondary-subtle"> Others from {{ recipe.category }}...</h4>
            {% for recipe in related_recipes %}
                <div class="col">
                <div class="card" style="width: 14rem;">
                    <a href="{% url 'recipe:detail' recipe.id %}" style="text-decoration: none">
                        <img src="{{ recipe.image.url }}" class="card-img-top" alt="...">
                  <div class="card-body">
                      <h4 class="card-title text-dark">{{ recipe.name }}</h4>
                      <div class="py-1">
                      {% for r in allrecipes %}
                        {% if forloop.counter <= recipe.difficulty %}
                             <i class="bi bi-star-fill text-warning" style="font-size: 1rem"></i>
                        {% endif %}
                      {% endfor %}
                    </div>
                      <h5 class="card-subtitle opacity-50 text-dark">{{ recipe.category }}</h5>
                      <p class="card-footer text-dark"><b>{{ recipe.created_by}}</b>'s recipe!</p>
                  </div>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>


    </div>
    </div>
{% endblock %}
```

recipe/templates/recipe/editRecipe.html
{% extends 'core/base.html' %}

{% block title %}
   Edit Recipe
{% endblock %}

{% block content %}
    <div class="px-3">
   <h1 class="pt-3">Edit {{ recipe.name }} here</h1>

   <form method="POST" action="." enctype="multipart/form-data">
      {% csrf_token %}

       <div class="p-4 fw-bold">
           {{ form.as_p }}
       </div>

   {% if form.errors or form.non_field_errors %}
                    <div class="mb-3 p-4 bg-danger rounded-3">
                        {% for field in form %}
                            {{ field.errors }}
                        {% endfor %}
                    {{ form.non_field_errors }}
                    </div>
                {% endif %}
    <div class="text-center">
        <button type="submit" class="btn btn-success px-3 text-center px-5 fw-bold">Edit</button>
    </div>
   </form>
    </div>
{% endblock %}
```

recipe/templates/recipe/likedRecipes.html
{% extends 'core/base.html' %}

{% block title %}
    Favourite Recipes
{% endblock %}

{% block content %}
    <div class="px-3">

    <h2 class="py-2"><i>{{ request.user.username }}'s favourite recipes:</i></h2>

    <div class="row">
        {% for recipe in liked_recipes %}
            <div class="col py-1">
                <div class="card" style="width: 18rem;">
                    <a href="{% url 'recipe:detail' recipe.id %}" style="text-decoration: none">
                        <img src="{{ recipe.image.url }}" class="card-img-top" alt="...">
                  <div class="card-body">
                      <h4 class="card-title text-dark">{{ recipe.name }}</h4>
                        <div class="py-1">
                      {% for r in allrecipes %}
                        {% if forloop.counter <= recipe.difficulty %}
                             <i class="bi bi-star-fill text-warning" style="font-size: 1rem"></i>
                        {% endif %}
                      {% endfor %}
                    </div>
                      <h5 class="card-subtitle opacity-50 text-dark">{{ recipe.category }}</h5>
                      <p class="card-text text-dark">{{ recipe.description }}</p>
                      <p class="card-footer text-dark"><b>{{ recipe.created_by}}</b>'s recipe!</p>
                  </div>
                    </a>
                </div>
            </div>
        {% endfor %}

    </div>

    <h4 class="text-center py-2 bg-secondary-subtle"> Other recipes you might like...</h4>

    <div class="row">
        {% for recipe in all_recipes %}
            {% if forloop.counter <= 5 %}
                <div class="col py-1">
                    <div class="card" style="width: 15rem;">
                        <a href="{% url 'recipe:detail' recipe.id %}" style="text-decoration: none">
                            <img src="{{ recipe.image.url }}" class="card-img-top" alt="...">
                      <div class="card-body">
                          <h4 class="card-title text-dark">{{ recipe.name }}</h4>
                            <div class="py-1">
                      {% for r in allrecipes %}
                        {% if forloop.counter <= recipe.difficulty %}
                             <i class="bi bi-star-fill text-warning" style="font-size: 1rem"></i>
                        {% endif %}
                      {% endfor %}
                    </div>
                          <h5 class="card-subtitle opacity-50 text-dark">{{ recipe.category }}</h5>
                          <p class="card-text text-dark">{{ recipe.description }}</p>
                          <p class="card-footer text-dark"><b>{{ recipe.created_by}}</b>'s recipe!</p>
                      </div>
                        </a>
                    </div>
                </div>
            {% endif %}
        {% endfor %}

    </div>



    </div>

{% endblock %}

recipe/templates/recipe/searchRecipe.html
{% extends 'core/base.html' %}

{% block title %}
   Search
{% endblock %}

{% block content %}
    <div class="px-3">
    <div class="top-search py-2" style="display: flex; justify-content: space-between">
        <div class="form-btn" style="display: flex; flex-direction: row">
            <h2><b>Search:</b></h2>
        <a href="{% url 'recipe:searchRecipe' %}" class="clear-btn py-1 px-3">
                <button class="btn btn-outline-danger rounded-5" type="reset">Clear search</button>
            </a>
        </div>
            <form method="get" action="{% url 'recipe:searchRecipe' %}" class="px-5" style="display: flex; flex-direction: row">
                            <input name="query" class="form-control px-2" type="text" value="{{ query }}" placeholder="I want to eat...">
                            <button class="bi bi-search btn btn-success rounded-5" type="submit"></button>
            </form>
    </div>

    <div class="container pt-4">
    <div class="row">
        {% for recipe in recipes %}
            <div class="col py-1">
                <div class="card" style="width: 18rem;">
                    <a href="{% url 'recipe:detail' recipe.id %}" style="text-decoration: none">
                        <img src="{{ recipe.image.url }}" class="card-img-top" alt="...">
                  <div class="card-body">
                      <h4 class="card-title text-dark">{{ recipe.name }}</h4>
                      <div class="py-1">
                      {% for r in allrecipes %}
                        {% if forloop.counter <= recipe.difficulty %}
                             <i class="bi bi-star-fill text-warning" style="font-size: 1rem"></i>
                        {% endif %}
                      {% endfor %}
                    </div>
                      <h5 class="card-subtitle opacity-50 text-dark">{{ recipe.category }}</h5>
                      <p class="card-text text-dark">{{ recipe.description }}</p>
                      <p class="card-footer text-dark"><b>{{ recipe.created_by}}</b>'s recipe!</p>
                  </div>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
    </div>
    </div>
{% endblock %}