core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm
from .views import logout_view

app_name = 'core'

urlpatterns = [
    path('', views.homePage, name='homePage'),
    path('about/', views.aboutPage, name='aboutPage'),
    path('signup/', views.signupPage, name='signupPage'),
    path('login/', auth_views.LoginView.as_view(template_name='core/loginPage.html', authentication_form=LoginForm), name='loginPage'),
    path('logout/', logout_view, name='logout'),
    path('category/<int:pk>/', views.categoryRecipes, name='categoryRecipes'),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboardPage, name='dashboardPage'),

]

receipt_website/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('recipes/', include('recipe.urls')),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe/urls.py
from django.urls import path
from . import views

app_name = 'recipe'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
    path('addRecipe/', views.addRecipe, name='addRecipe'),
    path('<int:pk>/delete/', views.deleteRecipe, name='deleteRecipe'),
    path('<int:pk>/edit/', views.editRecipe, name='editRecipe'),
    path('search/', views.searchRecipe, name='searchRecipe'),
    path('<int:pk>/likeRecipe/', views.likeRecipe, name='likeRecipe'),
    path('likedRecipes/', views.likedRecipes, name='likedRecipes'),
    path('deleteComment/<int:pk>/', views.deleteComment, name='deleteComment')
]

core/models.py
# Create your models here.

recipe/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class Recipe(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    ingredients = models.TextField()
    directions = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='recipe_images', blank=True)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    n_of_likes = models.IntegerField(default=0)
    difficulty = models.IntegerField(default=1)

    def __str__(self):
        return self.name


class LikeRecipe(models.Model):
    recipe_id = models.CharField(max_length=500)
    username = models.CharField(max_length=500)

    def __str__(self):
        return self.username


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    recipe = models.ForeignKey('Recipe', on_delete=models.CASCADE)
    content = models.TextField(max_length=100)

    def __str__(self):
        return self.user.username

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'es. MarioBros',
        'class': 'form-control py-2 px-3',
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'form-control py-2 px-3',
    }))

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'es. MarioBros',
        'class': 'form-control py-2 px-3',
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'es. mariobros@gmail.com',
        'class': 'form-control py-2 px-3',
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'form-control py-2 px-3',
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm your Password',
        'class': 'form-control py-2 px-3',
    }))

core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_protect

from recipe.models import Category, Recipe
from .forms import SignupForm
from django.contrib.auth import logout


# Create your views here.

def homePage(request):
    recipes = Recipe.objects.all().order_by('?')
    categorys = Category.objects.all()
    return render(request, 'core/homePage.html', {
        'recipes': recipes,
        'categorys': categorys,
    })


def aboutPage(request):
    return render(request, 'core/aboutPage.html')


@csrf_protect
def signupPage(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
        else:
            form = SignupForm()

    form = SignupForm()
    return render(request, 'core/signupPage.html', {
        'form': form
    })

@csrf_protect
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('core:homePage')


def categoryRecipes(request, pk):
    category = Category.objects.get(pk=pk)
    recipes = Recipe.objects.filter(category=category)

    return render(request, 'core/categoryRecipes.html', {
        'recipes': recipes,
        'category': category
    })

core/templates/core/aboutPage.html
{% extends 'core/base.html' %}

{% block title %}
    About
{% endblock %}
```

{% block content %}
    <div class="content px-3">
    <h1>About us:</h1>

<p>
    <b>Welcome to Student Recipes!</b> Since its inception in 2023, our website has been dedicated to providing a convenient and reliable resource for students to discover, create, and share delicious and affordable recipes.

At Student Recipes, we understand the challenges that come with being a student, especially when it comes to cooking and maintaining a healthy lifestyle. We believe that eating well shouldn't be complicated or expensive, and our mission is to empower students with the knowledge and inspiration they need to cook nutritious meals on a budget, using simple ingredients readily available in any student kitchen.

    Whether you're a seasoned chef or a novice in the kitchen, our platform offers a diverse collection of student-friendly recipes. From quick and easy meals for those hectic study nights to wholesome dishes that will impress your friends, we've got you covered.</p>

        <p>But <b>Student Recipes is more than just a recipe database</b>. It's a community of like-minded students passionate about food and cooking. Since 2023, we have been fostering a vibrant community where students can connect, exchange culinary tips and tricks, and share their own favorite recipes.

We also understand that dietary preferences and restrictions vary among students. That's why we provide a range of recipes to accommodate different dietary needs, including vegetarian, vegan, gluten-free, and more. Everyone is welcome here!

So, since 2023, Student Recipes has been your go-to destination for tasty and affordable meals. Join us in making cooking fun, accessible, and delicious for students everywhere!
</p>

    <hr>

    <div class="row">
        <div class="col-4 text-center">
            <a href="#" class="text-dark">Contact us </a>
        </div>
        <div class="col-4 text-center">
           <a href="#" class="text-dark"> Log-in </a>
        </div>
        <div class="col-4 text-center">
           <a href="#" class="text-dark"> Terms of use </a>
        </div>
    </div>
    </div>
{% endblock %}
```

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="wiewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">

    <title> {% block title %}{% endblock %}| Student Recipes</title>
</head>

<body>
<div class="base_navbar">
    <nav class="navbar navbar-dark bg-info">
        <div class="container-fluid">
            <a class="navbar-brand px-2" style="font-family: 'Lao MN'; font-size: 2rem" href="{% url 'core:homePage' %}">Student Recipes</a>
            <div class="items-navbar" style="display:flex; flex-direction: row">

            {% if request.user.is_authenticated %}
                <i class="px-5 py-3 text-light">Hi {{ request.user.username }}!</i>
            {% endif %}

            <a href="{% url 'recipe:searchRecipe' %}" class="search-btn py-2 px-2">
                        <i class="bi bi-search text-light" style="font-size: 1.5rem"></i>
            </a>

            {% if request.user.is_authenticated %}
                <div class="buttons_logged" style="display: flex; flex-direction: row">
                    <a href="{% url 'recipe:likedRecipes' %}" class="fav-btn px-3 pt-1" style="text-decoration: none">
                        <button type="button" href="#" class="btn btn-outline-danger border-2 text-light text-center">
                           <div class="d-flex align-items-center justify-content-center">
                               <b>Your likes</b> <i class="bi bi-suit-heart-fill text-light px-1" style="font-size: 1.5rem"></i>
                            </div>
                        </button>
                    </a>

                    <a href="{% url 'recipe:addRecipe' %}" class="new-recipe-btn px-2 py-2">
                        <button type="button" href="{% url 'recipe:addRecipe' %}" class="btn btn-success rounded-5 px-4">New Recipe</button>
                    </a>

                    <a href="{% url 'dashboard:dashboardPage' %}" class="profile-btn py-2" style="text-decoration: none">
                        <button type="button" class="btn btn-light rounded-5 px-4">Dashboard</button>
                    </a>

                    <form action="{% url 'core:logout' %}" method="post" class="px-2 py-2">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-light rounded-5 px-4">Logout</button>
                    </form>

                </div>

            {% else %}
                <div class="buttons px-3 py-2" style="display: flex">
                    <a class="login-btn" href="{% url 'core:loginPage' %}">
                        <button type="button" class="btn btn-primary rounded-5 px-4">Login</button>
                    </a>

                    <a class="register-btn px-2" href="{% url 'core:signupPage' %}">
                        <button type="button" class="btn btn-light rounded-5 px-4">Register</button>
                    </a>
            {% endif %}
                    <button class="navbar-toggler px-3 border-2 border-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="navigation switch">
                        <span class="navbar-toggler-icon border-light "></span>
                    </button>
                </div>
            </div>


            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link px-3 text-light" href="{% url 'core:homePage' %}">Home</a>
                    <hr>
                    <a class="nav-link px-3 text-light" href="{% url 'core:aboutPage' %}">About us</a>
                    <hr>

                    <form method="get" action="{% url 'recipe:searchRecipe' %}" class="px-5" style="display: flex; flex-direction: row">
                        <input name="query" class="form-control py-1 px-3" type="text" value="{{ query }}" placeholder="I want to eat...">
                        <button class="bi bi-search btn btn-success rounded-5" type="submit"></button>
                    </form>

                </div>
            </div>
        </div>
    </nav>
</div>

    {% block content %}
    {% endblock %}

<footer class="pt-4">
    <div class="container-fluid bg-info">
        <div class="row text-center" >
            <p class="text-light pt-2">Follow us on:</p>
            <div class="col-4"> <a href="https://www.facebook.com/"><i class="bi bi-facebook btn btn-outline-light btn-lg border-3"></i></a></div>
            <div class="col-4"><a href="https://www.instagram.com/"><i class="bi bi-instagram btn btn-outline-light btn-lg border-3"></i></a></div>
            <div class="col-4"><a href="https://www.twitter.com/"><i class="bi bi-twitter btn btn-outline-light btn-lg border-3"></i></a></div>
        </div>
        <div class="row">
            <div class="col-12 text-center pt-3">
                <p class="text-light">© 2023 Student Recipes</p>
            </div>
        </div>
    </div>
</footer>

</body>
</html>

core/templates/core/categoryRecipes.html
{% extends 'core/base.html' %}

{% block title %}
     {{ category.name }}
    {% endblock %}



{% block content %}
<div class="px-3">
    <h2 class="pt-2"><b>Recipes in {{ category.name }} category:</b></h2>

    <div class="container pt-4">
    <div class="row">
        {% for recipe in recipes %}
            <div class="col py-1">
                <div class="card" style="width: 18rem;">
                    <a href="{% url 'recipe:detail' recipe.id %}" style="text-decoration: none">
                        <img src="{{ recipe.image.url }}" class="card-img-top" alt="...">
                  <div class="card-body">
                      <h4 class="card-title text-dark">{{ recipe.name }}</h4>
                      <div class="py-1">
                      {% for r in recipes %}
                        {% if forloop.counter <= recipe.difficulty %}
                             <i class="bi bi-star-fill text-warning" style="font-size: 1rem"></i>
                        {% endif %}
                      {% endfor %}
                    </div>
                      <h5 class="card-subtitle opacity-50 text-dark">{{ recipe.category }}</h5>
                      <p class="card-text text-dark">{{ recipe.description }}</p>
                      <p class="card-footer text-dark"><b>{{ recipe.created_by}}</b>'s recipe!</p>
                  </div>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
    </div>

</div>

{% endblock %}

core/templates/core/homePage.html
{% extends 'core/base.html' %}


{% block title %}
    Home
{% endblock %}


{% block content %}
    <div style="display: flex; justify-content: center">
            <div class="main-cont__text border-1 text-center pt-2">
                <div class="row" style="display:flex; justify-content: space-around"><h1>Welcome to Student Recipes!</h1></div>
                <div class="row" style="display:flex; justify-content: space-around">Student Recipes is a website where you can find recipes for students.</div>
                <div class="row" style="display:flex; justify-content: space-around">Here you can find recipes for breakfast, lunch and dinner.</div>
                <div class="row" style="display:flex; justify-content: space-around">Enjoy!</div>
            </div>
    </div>
    <div class="inline text-center"><b>Number of <i class="bi bi-star-fill text-warning" style="font-size: 1rem"></i> means difficulty of recipe.</b></div>
<hr>
    <div class="categories-counter">
    <div class="row">
        {% for category in categorys %}

            <div class="col py-2 bg-secondary-subtle">
            <a href="{% url 'core:categoryRecipes' category.id %}" class="text-dark" style="text-decoration: none">
                <h4>{{ category.name }}s: {{ category.recipe_set.count }} </h4>
            </a>
            </div>

        {% endfor %}
    </div>
    </div>
<hr>
    <div class="container pt-4">
    <div class="row">
        {% for recipe in recipes %}
            <div class="col py-1">
                <div class="card" style="width: 18rem;">
                    <a href="{% url 'recipe:detail' recipe.id %}" style="text-decoration: none">
                        <img src="{{ recipe.image.url }}" class="card-img-top" alt="...">
                  <div class="card-body">
                      <h4 class="card-title text-dark">{{ recipe.name }}</h4>
                    <div class="py-1">
                      {% for r in recipes %}
                        {% if forloop.counter <= recipe.difficulty %}
                             <i class="bi bi-star-fill text-warning" style="font-size: 1rem"></i>
                        {% endif %}
                      {% endfor %}
                    </div>
                      <h5 class="card-subtitle opacity-50 text-dark">{{ recipe.category }}</h5>
                      <p class="card-text text-dark">{{ recipe.description }}</p>
                      <p class="card-footer text-dark"><b>{{ recipe.created_by}}</b>'s recipe!</p>
                  </div>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
    </div>

{% endblock %}

core/templates/core/loginPage.html
{% extends 'core/base.html'%}

{% block title %}
    Log-in
{% endblock %}

{% block content %}
    <div class="px-3">

    <h1 class="text-center pt-2">Log-in</h1>

    <div class="row justify-content-center">
        <div class="col-md-6 bg-secondary-subtle rounded-3">
            <form method="POST" action="." class="p-3">
                {% csrf_token %}

                <div class="mb-3">
                    {{ form.username.errors }}
                    <label for="id_username" class="form-label">Username</label> <br>
                    {{ form.username }}
                </div>

                <div class="mb-3">
                    {{ form.password.errors }}
                    <label for="passowrd" class="form-label">Password</label> <br>
                    {{ form.password }}
                </div>


                {% if form.errors or form.non_field_errors %}
                    <div class="mb-3 p-4 bg-danger rounded-3">
                        {% for field in form %}
                            {{ field.errors }}
                        {% endfor %}
                    {{ form.non_field_errors }}
                    </div>
                {% endif %}
                <div style="display: flex; justify-content: space-between">
                <button type="submit" class="btn btn-primary px-3">Log in</button>
                <a href="{% url 'core:signupPage' %}" class="btn btn-outline-dark">Do not have an account? Register here!</a>
                    </div>
            </form>

        </div>

    </div>
    </div>
{% endblock %}

core/templates/core/signupPage.html
{% extends 'core/base.html'%}

{% block title %}
    Sign-up
{% endblock %}

{% block content %}
    <div class="px-3">

    <h1 class="text-center pt-2">Sign-up</h1>

    <div class="row justify-content-center">
        <div class="col-md-6 bg-secondary-subtle rounded-3">
            <form method="POST" action="." class="p-3">
                {% csrf_token %}

                <div class="mb-3">
                    {{ form.username.errors }}
                    <label for="id_username" class="form-label">Username</label> <br>
                    {{ form.username }}
                </div>
                <div class="mb-3">
                    {{ form.email.errors }}
                    <label for="id_email" class="form-label">Email</label> <br>
                    {{ form.email }}
                </div>
                <div class="mb-3">
                    {{ form.password1.errors }}
                    <label for="passowrd1" class="form-label">Password</label> <br>
                    {{ form.password1 }}
                </div>
                <div class="mb-3">
                    {{ form.password2.errors }}
                    <label for="password2" class="form-label">Confirm password</label> <br>
                    {{ form.password2 }}
                </div>

                {% if form.errors or form.non_field_errors %}
                    <div class="mb-3 p-4 bg-danger rounded-3">
                        {% for field in form %}
                            {{ field.errors }}
                        {% endfor %}
                    {{ form.non_field_errors }}
                    </div>
                {% endif %}

                <div style="display: flex; justify-content: space-between">
                <button type="submit" class="btn btn-primary px-3">Submit</button>
                <a href="{% url 'core:loginPage' %}" class="btn btn-outline-dark px-3">Do you already have an account? Login here!</a>
                    </div>
            </form>
        </div>

    </div>
    </div>
{% endblock %}